from pathlib import Path
from typing import Optional

import yaml
from crewai import Agent, Crew, Task

from agentic_nas.data.hf_image_loader import DEFAULT_DENTEX_DATASET_ID
from agentic_nas.tools.dataset_tools import inspect_sleep_apnea_dataset, inspect_xray_dataset
from agentic_nas.tools.evaluation_tools import evaluate_nas_results
from agentic_nas.tools.reporting_tools import generate_nas_markdown_report
from agentic_nas.tools.training_tools import execute_builder_plan_with_optuna


BASE_DIR = Path(__file__).resolve().parent
CONFIG_DIR = BASE_DIR / "config"


def load_yaml(file_name: str) -> dict:
    with open(CONFIG_DIR / file_name, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def build_crew(
    profile_mode: str = "ecg",
    dataset_path: Optional[str] = None,
    hf_dataset_id: str = DEFAULT_DENTEX_DATASET_ID,
    hf_split: str = "train",
    hf_config_name: Optional[str] = None,
    include_trainer: bool = False,
    include_evaluator: bool = True,
    include_reporter: bool = True,
    trainer_trials: int = 50,
    report_output_path: Optional[str] = None,
) -> Crew:
    """
    Construir CrewAI com agentes de profiling e builder.

    Args:
        profile_mode: 'ecg' ou 'xray'
        dataset_path: path para ECG CSV
        hf_dataset_id: ID do dataset Hugging Face
        hf_split: split do HF dataset
        hf_config_name: config name do HF dataset
        include_trainer: se True, inclui TrainerAgent no crew (requires X,y data)
        trainer_trials: número de trials por family no Optuna

    Returns:
        Crew com agentes configurados
    """
    agents_config = load_yaml("agents.yaml")
    tasks_config = load_yaml("tasks.yaml")

    profiler_cfg = agents_config["dataset_profiler"]
    builder_cfg = agents_config["builder_agent"]

    profile_task_cfg = tasks_config["profile_dataset_task"]
    build_task_cfg = tasks_config["build_search_space_task"]

    if profile_mode == "ecg":
        if not dataset_path:
            raise ValueError("dataset_path is required when profile_mode='ecg'.")

        selected_tools = [inspect_sleep_apnea_dataset]
        dataset_context = (
            f"Profile mode: ECG CSV.\\n"
            f"Dataset path to inspect: {dataset_path}\\n"
            "Use tool: inspect_sleep_apnea_dataset(file_path=<dataset_path>)."
        )

    elif profile_mode == "xray":
        selected_tools = [inspect_xray_dataset]
        dataset_context = (
            f"Profile mode: X-ray image dataset via Hugging Face.\\n"
            f"Dataset id: {hf_dataset_id}\\n"
            f"Config name: {hf_config_name or '(default)'}\\n"
            f"Split preference: {hf_split}\\n"
            "Use tool: inspect_xray_dataset(dataset_id=<id>, split=<split>, config_name=<optional>)."
        )

    else:
        raise ValueError("profile_mode must be 'ecg' or 'xray'.")

    dataset_profiler = Agent(
        role=profiler_cfg["role"],
        goal=profiler_cfg["goal"],
        backstory=profiler_cfg["backstory"],
        tools=selected_tools,
        verbose=True,
        memory=False,
        allow_delegation=False,
    )

    builder_agent = Agent(
        role=builder_cfg["role"],
        goal=builder_cfg["goal"],
        backstory=builder_cfg["backstory"],
        tools=[],
        verbose=True,
        memory=False,
        allow_delegation=False,
    )

    profile_dataset_task = Task(
        name="profiling_agent",
        description=(
            f"{profile_task_cfg['description']}\\n\\n"
            f"Run context:\\n{dataset_context}\\n"
            "You must call the inspection tool before writing the report."
        ),
        expected_output=profile_task_cfg["expected_output"],
        agent=dataset_profiler,
    )

    build_search_space_task = Task(
        name="builder_agent",
        description=(
            f"{build_task_cfg['description']}\\n\\n"
            "Input: use only the profiler report generated by the previous task."
        ),
        expected_output=build_task_cfg["expected_output"],
        agent=builder_agent,
        context=[profile_dataset_task],
    )

    agents = [dataset_profiler, builder_agent]
    tasks = [profile_dataset_task, build_search_space_task]

    if include_evaluator and not include_trainer:
        raise ValueError("EvaluatorAgent requires include_trainer=True.")
    if include_reporter and not include_evaluator:
        raise ValueError("ReportAgent requires include_evaluator=True.")

    # Opcionalmente adicionar TrainerAgent
    if include_trainer:
        if profile_mode != "ecg":
            raise ValueError(
                "Trainer execution via Optuna is currently supported only for ECG mode."
            )
        trainer_cfg = agents_config.get("trainer_agent", {})
        train_task_cfg = tasks_config.get("train_search_space_task", {})

        trainer_agent = Agent(
            role=trainer_cfg.get("role", "Trainer"),
            goal=trainer_cfg.get("goal", "Train"),
            backstory=trainer_cfg.get("backstory", ""),
            tools=[execute_builder_plan_with_optuna],
            verbose=True,
            memory=False,
            allow_delegation=False,
        )

        train_search_space_task = Task(
            name="trainer_agent",
            description=(
                train_task_cfg.get("description", "Train")
                + "\\n\\nRun context:"
                + f"\\n- Dataset path: {dataset_path}"
                + f"\\n- Trials per family: {trainer_trials}"
                + "\\n\\nYou MUST call tool `execute_builder_plan_with_optuna` exactly once."
                + "\\nUse as input:"
                + "\\n- builder_output_json: strict JSON output from the previous builder task"
                + "\\n- dataset_path: the run context dataset path"
                + "\\n- n_trials_per_family: the run context trials value"
                + "\\n\\nReturn only the strict JSON output generated by the tool."
            ),
            expected_output=train_task_cfg.get("expected_output", "Results"),
            agent=trainer_agent,
            context=[build_search_space_task],
        )

        agents.append(trainer_agent)
        tasks.append(train_search_space_task)

        # Opcionalmente adicionar EvaluatorAgent
        if include_evaluator:
            evaluator_cfg = agents_config.get("evaluator_agent", {})
            evaluate_task_cfg = tasks_config.get("evaluate_models_task", {})

            evaluator_agent = Agent(
                role=evaluator_cfg.get("role", "Evaluator"),
                goal=evaluator_cfg.get("goal", "Interpret model performance"),
                backstory=evaluator_cfg.get("backstory", ""),
                tools=[evaluate_nas_results],
                verbose=True,
                memory=False,
                allow_delegation=False,
            )

            evaluate_models_task = Task(
                name="evaluator_agent",
                description=(
                    evaluate_task_cfg.get("description", "Evaluate model results")
                    + "\\n\\nYou MUST call tool `evaluate_nas_results` exactly once."
                    + "\\nUse as input:"
                    + "\\n- trainer_output_json: strict JSON output from the trainer task."
                    + "\\n\\nReturn only the strict JSON output generated by the tool."
                ),
                expected_output=evaluate_task_cfg.get("expected_output", "Results"),
                agent=evaluator_agent,
                context=[train_search_space_task],
            )

            agents.append(evaluator_agent)
            tasks.append(evaluate_models_task)

            # Opcionalmente adicionar ReportAgent
            if include_reporter:
                reporter_cfg = agents_config.get("report_agent", {})
                report_task_cfg = tasks_config.get("report_results_task", {})

                report_agent = Agent(
                    role=reporter_cfg.get("role", "Reporter"),
                    goal=reporter_cfg.get("goal", "Produce final markdown report"),
                    backstory=reporter_cfg.get("backstory", ""),
                    tools=[generate_nas_markdown_report],
                    verbose=True,
                    memory=False,
                    allow_delegation=False,
                )

                report_output_hint = report_output_path or "data/outputs/reports/nas_report.md"

                report_results_task = Task(
                    name="report_agent",
                    description=(
                        report_task_cfg.get("description", "Produce report")
                        + "\\n\\nYou MUST call tool `generate_nas_markdown_report` exactly once."
                        + "\\nUse as input:"
                        + "\\n- evaluator_output_json: strict JSON output from the evaluator task."
                        + f"\\n- output_path: {report_output_hint}"
                        + "\\n\\nReturn only the markdown report generated by the tool."
                    ),
                    expected_output=report_task_cfg.get("expected_output", "Markdown report"),
                    agent=report_agent,
                    context=[evaluate_models_task],
                )

                agents.append(report_agent)
                tasks.append(report_results_task)

    return Crew(
        agents=agents,
        tasks=tasks,
        verbose=True,
    )
