import argparse
import os
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv

from agentic_nas.artifacts import persist_agent_outputs
from agentic_nas.data.hf_image_loader import DEFAULT_DENTEX_DATASET_ID
from agentic_nas.crew import build_crew


def _env_to_bool(value: str | None, default: bool = False) -> bool:
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "y", "on"}


def run() -> None:
    project_root = Path(__file__).resolve().parents[2]
    load_dotenv(project_root / ".env")

    default_ecg_path = project_root / "data" / "raw" / "sleep_apnea_ecg.csv"

    parser = argparse.ArgumentParser(description="Run Agentic NAS dataset profiling.")
    parser.add_argument("--mode", choices=["ecg", "xray"], default=os.getenv("PROFILE_MODE", "ecg"))
    parser.add_argument("--dataset-path", default=os.getenv("ECG_DATASET_PATH", str(default_ecg_path)))
    parser.add_argument("--hf-dataset-id", default=os.getenv("HF_DATASET_ID", DEFAULT_DENTEX_DATASET_ID))
    parser.add_argument("--hf-config-name", default=os.getenv("HF_CONFIG_NAME"))
    parser.add_argument("--hf-split", default=os.getenv("HF_SPLIT", "train"))
    parser.add_argument("--output-file", default=os.getenv("PROFILE_OUTPUT_FILE"))
    parser.add_argument(
        "--trainer-trials",
        type=int,
        default=int(os.getenv("TRAINER_TRIALS", "5")),
        help="Number of Optuna trials per family for trainer agent.",
    )
    parser.add_argument(
        "--include-trainer",
        action=argparse.BooleanOptionalAction,
        default=_env_to_bool(os.getenv("INCLUDE_TRAINER"), default=False),
        help="Include trainer agent task in the crew run.",
    )
    parser.add_argument(
        "--include-evaluator",
        action=argparse.BooleanOptionalAction,
        default=_env_to_bool(os.getenv("INCLUDE_EVALUATOR"), default=False),
        help="Include evaluator agent task after trainer in the crew run.",
    )
    parser.add_argument(
        "--include-reporter",
        action=argparse.BooleanOptionalAction,
        default=_env_to_bool(os.getenv("INCLUDE_REPORTER"), default=False),
        help="Include report agent task after evaluator in the crew run.",
    )
    parser.add_argument(
        "--report-output-file",
        default=os.getenv("REPORT_OUTPUT_FILE"),
        help="Path to save the markdown report generated by report agent.",
    )
    args = parser.parse_args()

    output_root = project_root / "data" / "outputs"
    run_id = f"{datetime.now().strftime('%Y%m%d_%H%M%S')}_{args.mode}"
    run_dir = output_root / "runs" / run_id
    run_dir.mkdir(parents=True, exist_ok=True)

    report_output_file = args.report_output_file
    if args.include_reporter and not report_output_file:
        report_output_file = str(run_dir / "report.md")

    crew = build_crew(
        profile_mode=args.mode,
        dataset_path=args.dataset_path,
        hf_dataset_id=args.hf_dataset_id,
        hf_split=args.hf_split,
        hf_config_name=args.hf_config_name,
        include_trainer=args.include_trainer,
        include_evaluator=args.include_evaluator,
        include_reporter=args.include_reporter,
        trainer_trials=args.trainer_trials,
        report_output_path=report_output_file,
    )
    result = crew.kickoff()

    persist_agent_outputs(
        project_root=project_root,
        run_dir=run_dir,
        mode=args.mode,
        include_trainer=args.include_trainer,
        include_evaluator=args.include_evaluator,
        include_reporter=args.include_reporter,
        crew_result=result,
    )

    latest_run_file = output_root / "latest_run.txt"
    latest_run_file.parent.mkdir(parents=True, exist_ok=True)
    latest_run_file.write_text(str(run_dir.relative_to(project_root)), encoding="utf-8")

    if args.output_file:
        output_file = Path(args.output_file)
        if not output_file.is_absolute():
            output_file = project_root / output_file

        output_file.parent.mkdir(parents=True, exist_ok=True)
        output_file.write_text(str(result), encoding="utf-8")


if __name__ == "__main__":
    run()
